name: csi5138-project
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - altair=3.2.0=py37_0
  - python=3.7.3
  - pip=19.3.1
  - jupyterlab=1.1.4
  - ipywidgets=7.5.1
  - nodejs=10.13.0
  - pip:
    - matplotlib==3.1.1
    - tensorflow-datasets==1.3.0
    - tensorflow==2.0.0
    - plac
